### PR TITLE
CLI infer fix

### PR DESCRIPTION
**Pull request by a-little-srdjan**
fix for CLI infer

### CODE REVIEW

**Comment by vagmcs** [comment]
This does not seem right. Scala can cast Double to String when using string macro expressions like ${_targetCost}. Moreover, there are much more variables that work correctly. I changed the sbt scala version to 2.12.10 from 2.12.9 and it seems to work. I wonder if this was a bug of the scala compiler.

**Comment by a-little-srdjan** [comment]
Yeh it did look odd that only double failed. i’ll update sbt as well and give it a go.

**Comment by a-little-srdjan** [comment]
@anskarl you were spot on. changing the scala version fixed it. I re-ran the unit tests on this branch and all seems spiffy.

**Comment by anskarl** [comment]
@a-little-srdjan thanks for the contribution

**Pull request merged**
